import Language from '../../common/language';

const language: Language = {
    code: 'de',
    language: 'German',
    words: [
        'kostenlos',
        '100% unentgeltlich',
        'vergütung',
        'geschenk',
        'rückzahlung',
        'gebührenfrei',
        'kostenlos anmelden',
        'gratis testen',
        'gewinn',
        'reduktion',
        'rabatt',
        'bester preis',
        'angebot',
        'spezialangebot',
        'preise vergleichen',
        'für nur',
        'nicht teuer',
        'viel Geld sparen',
        'Gutschein',
        'kreditkarte',
        'bankkarte',
        'investition',
        'konkurs',
        'umsatz',
        'lohn',
        'zinssatz',
        'versicherung',
        'raus aus den schulden',
        'rückzahlung',
        'kredit',
        'bargeld',
        'hypotheken',
        'paypal',
        'bonus',
        'rendite',
        'visa',
        'mastercard',
        'cash',
        'geld',
        'einfach',
        'schnelles geld',
        'geld einnehmen',
        'zusatzeinkommen',
        'profitieren',
        'millionen',
        'sparen',
        'bester preis',
        'euro',
        'profit',
        'gewinn',
        'sei dein eigener chef',
        '€',
        '$',
        '£',
        'garantiert',
        '100% kostenlos',
        '100% sicher',
        'zertifiziert',
        'risikofrei',
        'angebot',
        'Bonus',
        'schnäppchen',
        'gesehen im TV',
        'deal',
        'es funktioniert',
        'keine abzocke',
        'kein spam',
        'keine versteckten kosten',
        'passwort',
        'persönliche angaben',
        'lieber freund',
        'singles kennenlernen',
        'bitte helfen',
        'jetzt spenden',
        'ihre Familie',
        'teenager',
        'hallo',
        'nicht löschen',
        'partnerschaft',
        'machen Sie schnell',
        'sofort',
        'jetzt profitieren',
        'limitiertes angebot',
        'ab jetzt',
        'nur heute',
        'zögern Sie nicht',
        'greifen Sie zu',
        'läuft bald ab',
        'Sie haben gewonnen',
        'bravo',
        'klicken',
        'um Ihr geschenk zu erhalten',
        'außergewöhnliches geschenk, gewinnen',
        'Sie wurden ausgewählt',
        'glückwunsch',
        'belohnung',
        'verkauf',
        'ausverkauf',
        'verkaufen Sie mehr',
        'erhöhen Sie Ihren Absatz',
        'hier klicken',
        'bestellen',
        'Jobangebot',
        'Umsatzzahlen',
        'Kaufen',
        'Marketing',
        'Erhöhen',
        'Gewicht verlieren',
        'schnell abnehmen',
        'zu viele Kilos',
        'wie abnehmen',
        'Diät',
        'Verjüngung',
        'Schonkost',
        'Erektion',
        'Falten',
        'Schnarchen',
        'Altern',
        'Glatze',
        'ohne Aufwand',
        'Ausdauer',
        'Valium',
        'Morphin',
        'Xanax',
        'Vardenafil',
        'Fluoxetin',
        'Viagra',
        'online Apotheke',
        'Medikamente',
        'Medizin',
        'Therapie',
        'Doktor',
        'Sex',
        'Treffen',
        'Singles',
        'heiß',
        'herbe',
        'Gras',
        'Weed',
        'Drogen',
        'Casino',
        'Blackjack',
        'Spielgeld',
        'Filme herunterladen',
        'streamen',
        'Werbung',
        '$$',
        'xxx',
        'über 18',
        'über 21',
        'Erwachsene',
        'Nur für Erwachsene',
        'Ab 18',
        '18+',
        'erotisch',
        'Sex',
    ]
}

export {language};