import Language from '../common/language';

const language: Language = {
    code: 'es',
    language: 'Spanish',
    words: [
        'aceptamos tarjetas de crédito',
        'compra directa',
        'cupón de oferta',
        'dirección de la facturación',
        'la mejor oferta',
        'llama ahora',
        'mejor precio',
        'oferta especial',
        'obtén ahora',
        'promoción especial',
        'gratis',
        '¿por qué pagar más?',
        'ahorra hasta',
        'llama gratis',
        'sin coste',
        'reserva ahora',
        '100 % stisfecho',
        'conoce solteros',
        'mujeres calientes',
        'hombres calientes',
        'sexo',
        'cita fácil',
        'querido amigo',
        'estimado amigo',
        'felicidades',
        'urgente',
        'ayuda por favor',
        'por favor lee',
        'cómo ganas más dinero',
        'trabaja desde casa',
        'gana dinero extra',
        'aumenta los ingresos',
        'ingreso extra',
        'has ganado',
        'dinero gratis',
        'casino',
        'comienza hoy',
        'notificación de depósito',
        'grandes ganancias',
        'sin riesgo',
        'sin trucos',
        'beneficio real',
        'elimina tu deuda',
        '¿has sido estafado?',
        'evita la bancarrota',
        'refinación',
        'reintegro total',
        'factura',
        'payPal',
        'visa',
        'mastercard',
        'fedEx',
        'en efectivo',
        'beneficiario',
        'ahorra mucho dinero',
        'inversión',
        'millones de euros',
        'millones de dólares',
        'cheque bancaria',
        'transferencia bancaria',
        'marketing online',
        'mayor tráfico por Internet',
        'marketing en Internet',
        'aumento de tráfico',
        'marketing directo',
        'aumenta las ventas',
        'soluciones de marketing',
        'prueba por un mes',
        'regístrate gratis hoy',
        'contactos gratis',
        'correo masivo',
        'farmacia online',
        'totalmente natural',
        'hormonas',
        'viagra',
        'pierde peso',
        'reducción drástica',
        'revierte la edad',
        'xanax',
        'medicina',
        'vicodin',
        'curar',
        'elimina las arrugas',
        'droga',
        '100%',
        'acceso gratuito',
        'regalo',
        '50% menos',
        'por solo',
        'descuento',
        'rebajas',
        'oferta',
        'compara precios',
        'menor precio',
        'menor tasa de interés',
        'ahorra',
        'compra',
        'compra directo',
        'click aquí',
        'presiona este vínculo',
        'gana dinero',
        'ingreso adicional',
        'compra dinero',
        'crédito',
        'financiación',
        'ganar',
        'gana',
        'ingresos',
        'reintegro total',
        'premios en efectivo',
        'beneficio total',
        'gana por semana',
        'maravilloso',
        'asombroso',
        'increíble',
        'sorpréndete',
        'tus ojos no lo creerán',
        'valores impresionantes',
        'hazlo ahora',
        'inscríbete ahora',
        'aprovecha hoy',
        'no puedes vivir sin',
        'hazlo hoy',
        'acceso instantáneo',
        'una vez en la vida',
        '¿qué espera?',
        'toma la decisión ahora',
        'por tiempo limitado',
        'correo prioritario',
        'sin costos ocultos',
        'visto en TV',
        'completamente natural',
        'cancelar en cualquier momento',
        'confidencialidad',
        'garantía',
        'seguro',
        'únete a millones de personas',
        'de acuerdo con las leyes',
        'satisfacción garantizada',
        'esto no es Spam',
        'para ti',
        'felicitaciones',
        'has sido seleccionado',
        'caliente',
        'agrandamiento',
        'solteras',
        'levitra',
        'hierbas',
        'tu propio jefe',
        'efectivo para tu trabajo',
        'mayor tráfico en Internet',
        'marketing por email',
        'nuevas extensiones de dominio',
        'no eliminar',
        'extranjero',
        'copia DVDs'
    ]
}

export {language};