import Language from "../common/language";

const language: Language = {
    code: 'fr',
    language: 'French',
    words: [
        'sexe',
        'hot',
        'sexy',
        'chaud',
        'viagra',
        'cure',
        'sexuel',
        'femme sexy',
        'homme sexy',
        'agrandissez votre pénis',
        'performance',
        'casino',
        'blackjack',
        'poker',
        'jetons',
        'mise',
        'roulette',
        'texas Hold\'em',
        'opportunité',
        'sans frais',
        'carte bancaire',
        'virement Paypal',
        'taux d\'intérêt',
        'meilleur prix',
        'prix les plus bas',
        'Moins de 50%',
        'Promotion spéciale',
        'Pour seulement',
        'Offre',
        'Gratuit',
        'Gratuite',
        '100% gratuit',
        'Installation gratuite',
        'Accès gratuit',
        'Échantillon gratuit',
        'Investissement gratuit',
        'Cadeau',
        'Annulation à tout moment',
        'Inscrivez-vous gratuitement aujourd’hui',
        'Nouveaux clients uniquement',
        'Obtenez-le maintenant',
        'Agissez dès maintenant',
        'Commandez aujourd’hui',
        'Qu’est-ce que vous at tendez',
        'Quantités limitées',
        'Temps limité',
        'Cliquez ici',
        'Profitez aujourd\'hui',
        'Bonjour',
        'Vous avez été sélectionné',
        'Ce n\'est pas un spam',
        'Ceci n\'est pas un spam',
        'Éliminer vos dettes',
        'Le taux d\'intérêt le plus bas',
        'Nous acceptons les cartes de crédit',
        'Bonne affaire',
        'Pas de frais',
        'Aucun risque',
        'Bon plan extraordinaire',
        'Félicitations',
        'Pour vous seulement',
        'Les meilleurs taux',
        'Incroyable',
        'remboursement intégral',
        'appels gratuits',
        'hosting gratuit',
        'argent gratuit',
        'rabais',
        'comparer les prix',
        'le taux d\'intérêt le plus bas',
        'pourquoi payer plus?',
        'acheter',
        'acheter directement',
        'appuyez sur ce lien',
        'cliquez sur ce lien',
        'faire de l\'argent',
        'gagner de l\'argent',
        'bonus d\'argent',
        'revenu supplémentaire',
        'de crédit',
        'de financement',
        'revenus',
        'augmenter les ventes',
        'le remboursement intégral',
        'des prix en argent',
        'd\'énormes profits',
        'par chèque',
        'par virement bancaire',
        'bénéfice total',
        'bénéfice réel',
        'merveilleux',
        'étonné',
        'vos yeux ne croiront pas',
        'des valeurs impressionnantes',
        'urgent',
        'maintenant',
        'faites-le maintenant',
        'appelez dès maintenant',
        'postulez dès maintenant',
        'profitez aujourd\'hui',
        'profitez dès aujourd\'hui',
        'ne peut pas vivre sans',
        'obtenir maintenant',
        'faire aujourd\'hui',
        'accès instantané',
        'commence aujourd\'hui',
        'une fois dans la vie',
        'qu\'est-ce que tu attends?',
        'faire le décision maintenant',
        'limitée dans le temps',
        'courrier prioritaire',
        'pas de risque',
        'pas de trucs',
        'pas de coûts cachés',
        '100% satisfait',
        'vu à la TV',
        'vu à la télé',
        'vu à la télévision',
        'tout à fait naturel',
        'd\'annuler à tout moment',
        'à la confidentialité',
        'l\'assurance',
        'rejoindre des millions de personnes',
        'selon les lois',
        'satisfaction garantie',
        'ce n\'est pas du spam',
        'instantané',
        'pour vous',
        'pour toi',
        'cher ami',
        'vous avez gagné',
        'rencontrer des célibataires',
        'pharmacie online',
        'médecine',
        'vicodin',
        'levitra',
        'valium xanax',
        'valium',
        'xanax',
        'herbes',
        'hormones',
        'perdre du poids',
        'renverse l\'âge',
        'être votre propre patron',
        'travailler à domicile',
        'efficace pour votre travail',
        'marketing online',
        'plus de trafic dans Internet',
        'marketing direct',
        'email marketing',
        'nouvelles extensions de domaine',
        'ne pas supprimer',
        'étrangers',
        '100%',
        '#1',
        '$$$',
        '50%',
        'Copiez les DVD',
    ]
}
export {language};