import Language from "../../common/language";

const language: Language = {
    code: 'it',
    language: 'Italian',
    words: [
        '#1',
        'Soddisfatti al 100%',
        '4U',
        'Accetta carte di credito',
        'Agisci adesso!',
        'reddito supplementare',
        'Affordable',
        'Tutto naturale',
        'Tutto nuovo',
        'Stupefacente',
        'Applicare online',
        'Affare',
        'Miglior prezzo',
        'Indirizzo Di Fatturazione',
        'acquistare direttamente',
        'Chiamata',
        'Chiama gratis',
        'Non può vivere senza',
        'carte accettate',
        'Centesimi sul dollaro',
        'Dai un\'occhiata',
        'Reclami',
        'Clic',
        'Clicca qui',
        'Clicca per rimuovere',
        'Confronta i prezzi',
        'Complimenti',
        'Costo',
        'Nessun costo',
        'caro amico',
        'Farlo oggi',
        'Entrate extra',
        'Gratuito',
        'Modulo',
        'E la connessione',
        'installazione gratuita',
        'libero porta',
        'Iscrizione gratuita',
        'offerta libera',
        'anteprima gratuita',
        'Free website',
        'rimborso totale',
        'Scaricalo ora',
        'Dando via',
        'Garanzia',
        'Qui',
        'Nascosto',
        'Aumento delle vendite',
        'Aumenta il traffico',
        'Informazioni richieste',
        'Assicurazione',
        'Investimento',
        'nessun investimento',
        'decisione di investimento',
        'legale',
        'Perdere',
        'Marketing',
        'soluzioni di marketing',
        'Il messaggio contiene',
        'I soldi',
        'Mese offerta di prova',
        'Nome della marca',
        'Mai',
        'Nessuna trovata pubblicitaria',
        'Non ci sono costi nascosti',
        'Nessun obbligo',
        'Adesso',
        'Offrire',
        'Una volta',
        'Una volta',
        'Opportunità',
        'Ordine',
        'Se fate un ordine',
        'Lo stato dell\'ordine',
        'Gli ordini spediti per posta prioritaria',
        'Prestazione',
        'Telefono',
        'Si prega di leggere',
        'I potenziali guadagni',
        'Pre approvato',
        'Prezzo',
        'Stampare e fax',
        'I profitti',
        'Cosa vera',
        'istruzioni per la rimozione',
        'Rimuovere',
        'Privo di rischio',
        'Vendite',
        'Soddisfazione garantita',
        'Salva $',
        'Risparmiare fino a',
        'Motori di ricerca',
        'Vedere per credere',
        'contanti grave',
        'Soluzione',
        'Promozione speciale',
        'Successo',
        'Il modulo seguente',
        'Indesiderata',
        'Annulla l\'iscrizione',
        'Urgente',
        'dollari americani',
        'Moglie',
        'Vincere',
        'Vincitore',
        'Lavoro a casa',
        'Annunci',
        'Ordina',
        'Incrementa le tue vendite',
        'Mercato Internet',
        'Mass Mail',
        'Più traffico internet',
        'Fare soldi',
        'Vendita',
        'Lista dei motori di ricerca',
        'Questo non è spazzatura',
        'Cash',
        'A buon mercato',
        'Esplodere il tuo business',
        'Eliminare il debito',
        'Acquista',
        'Clicca sotto',
        'Direct Marketing',
        'Form',
        'Incrementa il traffico',
        'Acquirente',
        'Gareggia per il tuo business',
        'Beneficiario',
        'Questo non è spam',
        'Traffico web',
        'Profitto',
        'Richiedere investimento iniziale',
        'Fatti pagare',
        'Clicca',
        'Email Marketing',
        'Incremento vendite',
        'Internet Marketing',
        'Soluzioni Marketing',
        'Prova offerta del mese',
        'Marketing online',
        'Performance',
        'Abbonarsi',
        'Visita il nostro sito',
        'Cash bonus',
        'Credito',
        'Quote',
        'Consolidare debiti e crediti',
    ]
}
export {language};