import Language from "../../common/language";

const language: Language = {
    code: 'pt',
    language: 'Portuguese',
    words: [
        'GRÁTIS',
        'Atenção',
        'Oi',
        'Urgente',
        'Imediato',
        'Amigo',
        'Escondido',
        'Para você',
        'PARE',
        'Desconto',
        'Oferta',
        'Agora',
        'Quente',
        'Incrível',
        'Satisfação',
        'Faça agora',
        'Aplique agora',
        'Como visto',
        'Como visto na TV',
        'Evite',
        'Seja seu próprio chefe',
        'Trabalhe de casa',
        'Negócio caseiro',
        'Compre',
        'Ligue agora',
        'Bônus em dinheiro',
        'Dinheiro de graça',
        'Dobre sua renda',
        'Ganhe $',
        'Marketing multinível',
        'Ganhe dinheiro',
        'Faça dinheiro',
        'Dinheiro de verdade',
        'Como ganhar dinheiro',
        'Renda extra',
        'Dinheiro rápido',
        'Pagamento imediato',
        'Seu pagamento atrasado',
        'Gestão de fundos',
        'Acesso gratuito',
        'Presente gratuito',
        'Informação gratuita',
        'Informação que você solicitou',
        'Veja isso',
        'Oferta gratuita',
        'Liberdade financeira',
        'Remédios',
        'Comprimidos',
        'Pílulas',
        'Rivotril',
        'Diazepam',
        'Vicodin',
        'Viagra',
        'Levitra',
        'Plantas medicinais',
        'Aumente',
        'Clique aqui',
        'Abra agora',
        'Dê uma olhada',
        'Leia agora',
        'Não apague',
        'Isso não é spam',
        'Receba',
        'Compare',
        'Fortaleça',
        '$$$',
        'Crédito',
        'Débito',
        'Saia das dívidas',
        'Acabe com suas dívidas',
        'Taxas reduzidas',
        'Refinanciamento',
        'Menores taxas de seguro',
        'Seguro de vida',
        'Empréstimos',
        'Querido amigo',
        'Desconto',
        'Perca peso',
        'Graduação online',
        'Marketing online',
        'Farmácia online',
        'Oportunidade',
        'Garantido',
        'Sites de busca',
        'Adolescente',
        'Vencedor',
        'Você é um vencedor',
        'Sua família',
        'Seu email ganhou',
        'Por favor me ajude',
        'Pedido de parceria',
        'Deus te abençoe',
        'Compre agora',
        'Tempo limitado',
        'Destinatário desconhecido',
        'Aplicações Online',
        'Ganhe bilhões',
        'Aproveite',
        'Promoção',
        'Imperdível',
        'Preços',
        'Valores',
        'Última chance',
        'Hoje',
        'Não perca tempo',
        '24 horas',
        'Só até amanhã',
        'Clique',
        'Assine',
        'Visite o site',
        'Saiba mais',
        'Não exclua',
        'Confira',
        'Abra',
        'Especialmente para você',
        'A informação que você pediu',
        'Vagas abertas',
        'Telemarketing',
        'Curso',
        'Agência de modelos',
        'Oferta de emprego',
        'Parceria',
        'Divulgue seu',
        'Divulgue sua',
        'Marketing',
        'Trabalhe em casa',
        'Dinheiro',
        'Seja seu próprio patrão',
        'Taxas baixas',
        'Pago semanalmente',
        'Dinheiro a sério',
        'Saia da dívida',
        'Elimine a dívida',
        'Reduza suas taxas',
        'Refinancie',
        'Bônus',
        'Livre',
        '100%',
        'Emagreça',
        'Dieta',
        'Por que não consigo emagrecer',
        'Perder gordura',
        'Fique sarado',
        'Secar barriga',
    ]
}
export {language};